# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_tor',
            new_name='user_to',
        ),
    ]
